RegisterNUICallback('adminSearchPlayer', function(data, cb) cb(lib.callback.await('tommy_boosting:cb:adminSearchPlayer', false, data)) end)
RegisterNUICallback('adminAddCrypto', function(data, cb) cb(lib.callback.await('tommy_boosting:cb:adminAction', false, 'add_crypto', data)) end)
RegisterNUICallback('adminRemoveCrypto', function(data, cb) cb(lib.callback.await('tommy_boosting:cb:adminAction', false, 'remove_crypto', data)) end)
RegisterNUICallback('adminAddXP', function(data, cb) cb(lib.callback.await('tommy_boosting:cb:adminAction', false, 'add_xp', data)) end)
RegisterNUICallback('adminRemoveXP', function(data, cb) cb(lib.callback.await('tommy_boosting:cb:adminAction', false, 'remove_xp', data)) end)
RegisterNUICallback('adminSetXP', function(data, cb) cb(lib.callback.await('tommy_boosting:cb:adminAction', false, 'set_xp', data)) end)
RegisterNUICallback('adminGenerateContract', function(data, cb) cb(lib.callback.await('tommy_boosting:cb:adminAction', false, 'generate_contract', data)) end)
RegisterNUICallback('adminCancelContract', function(data, cb) cb(lib.callback.await('tommy_boosting:cb:adminAction', false, 'cancel_contract', data)) end)
RegisterNUICallback('adminForceComplete', function(data, cb) cb(lib.callback.await('tommy_boosting:cb:adminAction', false, 'force_complete', data)) end)
RegisterNUICallback('adminGetLogs', function(_, cb) cb(lib.callback.await('tommy_boosting:cb:adminGetLogs', false)) end)
