RegisterNUICallback('acceptContract', function(data,cb) TriggerServerEvent('tommy_boosting:server:acceptContract', data.index); cb(1) end)
RegisterNUICallback('completeContract', function(_,cb) local ped=PlayerPedId(); local veh=GetVehiclePedIsIn(ped,false); local c=GetEntityCoords(ped); TriggerServerEvent('tommy_boosting:server:completeContract', VehToNet(veh), {x=c.x,y=c.y,z=c.z}); cb(1) end)
RegisterNUICallback('buyStoreItem', function(data,cb) TriggerServerEvent('tommy_boosting:server:buyItem', data.item); cb(1) end)
RegisterNUICallback('vinScratch', function(_,cb) TriggerServerEvent('tommy_boosting:server:vinScratch'); cb(1) end)
RegisterNUICallback('getHistory', function(_,cb) cb(lib.callback.await('tommy_boosting:cb:getHistory', false)) end)
RegisterNUICallback('getLeaderboard', function(_,cb) cb(lib.callback.await('tommy_boosting:cb:getLeaderboard', false)) end)
RegisterNetEvent('tommy_boosting:client:acceptResult', function(ok,data) if ok then LocalState.activeContract=data; TriggerEvent('tommy_boosting:client:startContract',data); Bridge.Notify(cache.serverId,'Contract accepted','success') else Bridge.Notify(cache.serverId,data,'error') end end)
RegisterNetEvent('tommy_boosting:client:completeResult', function(ok,data) if ok then TriggerEvent('tommy_boosting:client:contractCompleted',data); Bridge.Notify(cache.serverId,'Contract delivered','success') else Bridge.Notify(cache.serverId,data,'error') end end)
